version: '2'
services:
  db:
    container_name: scinote_db_development
    image: postgres:11
    volumes:
      - scinote_development_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: scinote_web_development
    container_name: scinote_web_development
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: >
      bash -c "rm -f /usr/src/app/tmp/pids/server.pid &&
               yarn install &&
               (bundle check || bundle install) &&
               ./bin/dev"
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - scinote_development_bundler:/usr/local/bundle/
      - scinote_development_files:/usr/src/app/public/system
      - scinote_development_storage:/usr/src/app/storage

volumes:
  scinote_development_postgres:
  scinote_development_bundler:
  scinote_development_files:
  scinote_development_storage:
